name: CI/CD Pipeline

# Trigger the pipeline on push to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # JOB 1: Test and Security Scan
  test-and-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit

      - name: Run Security Scan (SAST)
        # -r app/: Recursive scan of app folder
        # -s B101: Skip rule B101 (assert statements used in tests)
        run: bandit -r app/ -s B101

      - name: Run Unit Tests
        run: pytest

  # JOB 2: DAST Security Scan
  dast_scan:
    needs: test-and-security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Run App Container
        run: |
          docker build -t test-app .
          docker run -d --name test-app -p 8000:8000 test-app
          sleep 10 # Wait for app to startup

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:8000'
          
  # JOB 3: Build and Push Docker Image
  build-and-push:
    needs: [test-and-security, dast_scan]  # Run only if tests and scans pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simple-todo-app:latest